import { Product } from "@shared/contracts/product-contracts";

export const demoProducts = [
    {
        ...new Product,
        _id: "urn:pistacho:id:5f7c3c5a0a8a9d001d1c2e3f",
        _schema: "urn:pistacho:schema:Product",
        _c: "2022-03-31T16:00:00.000Z",
        _label: "Aceite De Coco Neutro God Bless You X 125Ml",
        productGroup: "Aceites",
        sKU: 1,
        barcode: "2402241547326",
        measurementUnit: "u",
        cost: 3564,
        markup: 100,
        price: 7128,
        tax: null,
        isTaxInclusivePrice: 1,
        isPriceChangeAllowed: 0,
        isUsingDefaultQuantity: 0,
        isService: 0,
        isEnabled: 1,
        description: "",
        quantity: 0,
        supplier: null,
        reorderPoint: null,
        preferredQuantity: null,
        lowStockWarning: null,
        warningQuantity: null,
        proveedor: 'Biomega'
    },
    {
        ...new Product,
        _id: "urn:pistacho:id:5f7c3c5a0a8a9d001d1c2e3g",
        _schema: "urn:pistacho:schema:Product",
        _c: "2022-03-31T16:00:00.000Z",
        _label: "Aceite De Lino Prensado En Frio Vitalika 250Cc",
        productGroup: "Aceites",
        sKU: 2,
        barcode: "2402241547327",
        measurementUnit: "u",
        cost: 1936,
        markup: 100,
        price: 3872,
        tax: null,
        isTaxInclusivePrice: 1,
        isPriceChangeAllowed: 0,
        isUsingDefaultQuantity: 0,
        isService: 0,
        isEnabled: 1,
        description: "",
        quantity: 0,
        supplier: null,
        reorderPoint: null,
        preferredQuantity: null,
        lowStockWarning: null,
        warningQuantity: null,
        proveedor: 'Biomega'
    },
    {
        ...new Product,
        _id: "urn:pistacho:id:5f7c3c5a0a8a9d001d1c2e3h",
        _schema: "urn:pistacho:schema:Product",
        _c: "2022-03-31T16:00:00.000Z",
        _label: "Aceite Oliva Fincas Riojanas 1L (Pet)",
        productGroup: "Aceites",
        sKU: 3,
        barcode: "2402241547328",
        measurementUnit: "u",
        cost: 4016,
        markup: 100,
        price: 8032,
        tax: null,
        isTaxInclusivePrice: 1,
        isPriceChangeAllowed: 0,
        isUsingDefaultQuantity: 0,
        isService: 0,
        isEnabled: 1,
        description: "",
        quantity: 0,
        supplier: null,
        reorderPoint: null,
        preferredQuantity: null,
        lowStockWarning: null,
        warningQuantity: null,
        proveedor: 'Biomega'
    },
    {
        ...new Product,
        _id: "urn:pistacho:id:5f7c3c5a0a8a9d001d1c2e3i",
        _schema: "urn:pistacho:schema:Product",
        _c: "2022-03-31T16:00:00.000Z",
        _label: "Aji Molido",
        productGroup: "Especias",
        sKU: 4,
        barcode: "2402241547329",
        measurementUnit: "kg",
        cost: 9566,
        markup: 100,
        price: 19132,
        tax: null,
        isTaxInclusivePrice: 1,
        isPriceChangeAllowed: 0,
        isUsingDefaultQuantity: 0,
        isService: 0,
        isEnabled: 1,
        description: "",
        quantity: 0,
        supplier: null,
        reorderPoint: null,
        preferredQuantity: null,
        lowStockWarning: null,
        warningQuantity: null,
        proveedor: 'El semillero'
    }
]